### PR TITLE
Auto-parse links (fixes Issue #9)

### PR DESCRIPTION
**Pull request by samskiter**
see https://api.slack.com/docs/formatting

### CODE REVIEW

**Comment by samskiter** [comment]
This would also depend on removing the triple backticks from responses... maybe need a command line switch for the triple backticks?

**Comment by Chikashi-Kato** [comment]
Thank you for improving slacktee!
Yeah, having a command line switch for the triple backticks is good idea. In some cases, we don't want to show the output as pre-formatted text.
Also, I prefer to have another command line switch for 'parse=full' option which is turned-off by default. I'm a little bit worry that slacktee unexpectedly sends unnecessary notification to users a lot.

Could you implement these options?
If it's tough, please let me know. I will work on it. :)

Again, thank you so much for contributing slacksee!!

**Comment by samskiter** [comment]
I'll have a go now. Are you happy with one merge request for both
features?? What would you like the defaults to be?

**Comment by Chikashi-Kato** [comment]
One merge request for both features is fine for me.
By default, I'd like to disable 'perse=full' and enable triple backticks formatting.
I really appreciate your great contribution!

**Comment by samskiter** [comment]
Hi, I've updated the MR. you might want to tweak the names of the command line option as well as the help information printed out. I realised that if triple back-ticks was enabled, the parse option would have no effect (as slack won't try to find links inside the code block). So to avoid confusion, I have one command line option with 3 possible values that represent the 3 possible combinations that make sense.

**Comment by Chikashi-Kato** [comment]
Great implementation!! I will test it on my side quickly and merge it into master branch.
I really appreciate your contribution. It's awesome!!

**Comment by Chikashi-Kato** [comment]
I found a backward compatibility issue in the file uploading mode (with -f option).
Originally, open and download URL have been linked to the file, but they were not linked in new version.
To fix this issue, I separated out the plain text option (-p option) from the message formatting option.

Also, I added 'link_names' mode to the message formatting option.
In many cases, 'link_names' mode is more useful than 'full' mode.

If you find any issues in my code, please feel free to let me know.
Again, I really appreciate your great contribution!!!

**Comment by samskiter** [comment]
Thanks! I hadn't noticed that slack parses URLs inside code blocks....

**Comment by Chikashi-Kato** [comment]
Yeah, it's a little bit funky behavior :stuck_out_tongue_winking_eye:

**Pull request merged**
