### PR TITLE
Fix shellcheck

### PR DESCRIPTION
**Pull request by spk**
Some shellcheck fixe, thanks

### CODE REVIEW

**Comment by Chikashi-Kato** [comment]
Thank you for contributing to slacktee project, spk! You made the code cleaner :)

After the merge, I fixed following issues.
- -f option didn't work
- unnecessary curl's output "ok" was displayed

Since it's tough to test all options manually, please use test.sh.
It automatically tests almost of all options. (You still need to check the result though)

Ideally, slacktee.sh should have unittest, but I have never seen any unittest framework for bash scripts. 
If you know anything about the unittest framework, please let me know :)

**Comment by spk** [comment]
Thank you for this useful script !
Sorry for the issues, I did not test the attachment part.
I never work with unittest for bash script too.

**Comment by Chikashi-Kato** [comment]
I'm really glad slacktee works for you :)

**Comment by spk** [comment]
I just discover [bats](https://github.com/sstephenson/bats) which look interesting

**Comment by Chikashi-Kato** [comment]
Oh nice! Thank you so much for the information. I will check it!

**Pull request merged**
