### PR TITLE
Fix case between one or multiple lines of input (in buffered mode)

### PR DESCRIPTION
**Pull request by jovandeginste**

### CODE REVIEW

**Comment by Chikashi-Kato** [comment]
I'd like to check this bug on my side before merging your pull request, but could you give me an example which I can use to reproduce the bug?

**Comment by jovandeginste** [comment]
I was trying to provide a clear explanation of behavior before and after the PR, but I now see Github has still a different approach to Markdown backticks (and I will assume their approach is correct). I will tinker a bit more with this and provide feedback!

**Comment by jovandeginste** [comment]
OK, I did some more extensive tests, including with slack.com, and now have something that works both for Mattermost and Slack correctly. The previous behavior worked for slack, because slack apparently doesn't care for syntax highlighting in Markdown :-)

The following is correct markdown (except for two backticks instead of three):

```
``ruby
class A
  def x
    puts 5
  end
end
``
```

On Github, and someday on Mattermost, this will show as follows:

```ruby
class A
  def x
    puts 5
  end
end
```

On Slack this shows as follows:

```
ruby
class A
  def x
    puts 5
  end
end
```

Maybe Slack will support syntax highlighting too someday?

**Comment by Chikashi-Kato** [comment]
Sorry, I couldn't reproduce this issue on my local, but could you provide me test data?

**Comment by jovandeginste** [comment]
Yes, you can not reproduce this on slack - there is no issue when talking to a slack back-end. 

I am now working with a mattermost back-end and tried using all the same scripts I used for slack. This was one issue, different behavior between slack and mattermost. 

I chose to name it a bug, because now it adheres to the markdown specs...

**Comment by Chikashi-Kato** [comment]
Ah, I see! Thank you for the explanation.
Now this branch has a merge conflict, so I will resolve it and test the code, then merge this PR.
Sorry for taking long time to accept this PR!

**Comment by Chikashi-Kato** [comment]
Again, sorry for taking a long time to accept this PR!
I really appreciate your great effort to improve slacktee!!

**Comment by jovandeginste** [comment]
No problem, I had an extended weekend so I was not really anxious :-)

Would you mind a pull request where I auto-indent all the code?

**Comment by Chikashi-Kato** [comment]
Nope. As long as it doesn't break any functionalities and makes code more readable, I would love to merge the request into master :)

**Pull request merged**
