### PR TITLE
added no output option

### PR DESCRIPTION
**Pull request by xavier-re**
convenient for some bash scripts

### CODE REVIEW

**Comment by Chikashi-Kato** [comment]
Hi xavier-re, thank you so much for the PR!
I would like to understand cases where the option is helpful before merging it, but could you let us know about it?
Doesn't `> /dev/null` (redirecting the output to `/dev/null`) work in the case?

**Comment by xavier-re** [comment]
> I would like to understand cases where the option is helpful before merging it, but could you let us know about it?
> Doesn't `> /dev/null` (redirecting the output to `/dev/null`) work in the case?


in general, i think it would do the same.

for me it's a lot better : i add it to a script, so it's cleaner.
it's removing only the normal line by line output of slacktee, which is better 
than removing everything. 

also, there might be some use cases where we want to print to stdout without printing the line each time.

morever, it also adds the capability for slacktee to become a generic post to slack shell script.

thanks !

**Comment by Chikashi-Kato** [comment]
Thank you for the explanation. I will test your code and then merge it into master.
Please give us a little bit more time! Thanks.

**Comment by Chikashi-Kato** [comment]
- Cleaned up some indentations
- Added the new option to the help
- Added the test cases

**Comment by xavier-re** [comment]
On 2017.10.03 21:10:15 EDT, Chikashi Kato wrote:
> - Cleaned up some indentations
> - Added the new option to the help
> - Added the test cases
> 


good job !

**Pull request merged**
